# Generated by Django 6.1.2 on 2026-10-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='email',
            new_name='assignee_email',
        ),
    ]
