# Generated by Django 6.1.2 on 2026-10-08 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_email_task_assignee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remind_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='remind_before_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
